# Generated by Django 3.2.4 on 2021-06-23 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='body',
            field=models.TextField(default='Body Field'),
            preserve_default=False,
        ),
    ]
