# Generated by Django 3.2.4 on 2021-07-30 08:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0005_auto_20210723_1116'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConferenceArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('pub_date', models.DateField(blank=True, default=None)),
                ('description', models.TextField(default='No description')),
                ('co_authors', models.CharField(default=None, help_text='enter coauthors seperated by commas', max_length=200)),
                ('conference_name', models.CharField(blank=True, max_length=200, null=True)),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
                ('organised_date', models.DateField(blank=True, default=models.DateField(blank=True, default=None), null=True)),
                ('conference_link', models.URLField(default=None)),
                ('author', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('pub_date', models.DateField(blank=True, default=None)),
                ('description', models.TextField(default='No description')),
                ('co_authors', models.CharField(default=None, help_text='enter coauthors seperated by commas', max_length=200)),
                ('edition', models.CharField(blank=True, max_length=50, null=True)),
                ('isbn', models.CharField(blank=True, max_length=50, null=True)),
                ('chapters', models.CharField(blank=True, max_length=50, null=True)),
                ('book_link', models.URLField(default=None)),
                ('author', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
