# Generated by Django 3.2.4 on 2021-08-08 02:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0006_book_conferencearticle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='citations',
        ),
        migrations.RemoveField(
            model_name='conferencearticle',
            name='location',
        ),
        migrations.AddField(
            model_name='conferencearticle',
            name='pages',
            field=models.CharField(blank=True, help_text='must be in form nn--nn', max_length=50),
        ),
        migrations.AddField(
            model_name='conferencearticle',
            name='volume',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_link',
            field=models.URLField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='journals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='article',
            name='co_authors',
            field=models.CharField(default=None, help_text='enter coauthors seperated by and', max_length=200),
        ),
        migrations.AlterField(
            model_name='article',
            name='pages',
            field=models.CharField(blank=True, help_text='must be in form nn--nn', max_length=50),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='books', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_link',
            field=models.URLField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='conferencearticle',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='conferenceArticle', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='conferencearticle',
            name='conference_link',
            field=models.URLField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='conferencearticle',
            name='organised_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
