# Generated by Django 3.2.4 on 2021-08-08 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_auto_20210808_0747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conferencearticle',
            name='organised_date',
        ),
        migrations.AddField(
            model_name='conferencearticle',
            name='publisher',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
