# Generated by Django 3.2.4 on 2021-08-17 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_auto_20210815_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='journal_ID',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='book',
            name='book_ID',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='conferencearticle',
            name='conference_ID',
            field=models.CharField(default='', max_length=100),
        ),
    ]
